import type { Href } from 'expo-router';

/**
 * World Cup routes live under `app/(wc2026)/`. Typed routes (`/.expo/types/router.d.ts`)
 * are regenerated by Expo tooling; this escape hatch keeps navigation type-safe enough to compile.
 */
export function wcHref(path: string): Href {
  return path as unknown as Href;
}

/** Use for `router.push({ pathname, params })` — typed-route `pathname` is stricter than `wcHref` alone. */
export function wcHrefWithParams(pathname: string, params?: Record<string, string>): Href {
  return (params ? { pathname, params } : { pathname }) as unknown as Href;
}
